-- apply changes
create table url (
  id                            bigint generated by default as identity not null,
  created_at                    timestamp not null,
  name                          text,
);

