<html lang="ru">
<head>
    <div class="p-3 mb-2 bg-dark text-white">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
          crossorigin="anonymous">
    <title>Анализатор страниц</title>
    <h1> Анализатор страниц </h1>
    <h6>Бесплатно проверяйте сайты на SEO пригодность</h6>
    <p><input type="search" name="q" placeholder="Ссылка">
        <button type="button" class="btn btn-primary">Проверить</button></p>
    </div>
</head>
</html>
